server:
  port: 8888

spring:
  datasource:
    url: jdbc:h2:mem:students
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop